### ISSUE TITLE
0 watt reading

### ISSUE THREAD

**Issue by rolfie23** [mk01/shelly-2to1-mqtt#7]
Since a update to the 1.0 firmware on the shelly gen 2 when I have no usage, the actual power goes to 1e-07 see following picture:
![Schermafbeelding 2023-08-16 220000](https://github.com/mk01/shelly-2to1-mqtt/assets/61058985/52763ab6-5069-4d0f-a51a-9deff8be97e8)
It means domoticz get an value of 0.0000001 watt. Is it posible to make this 0?'
This is on a 1PM, a 2PM shows 2e-7 witch means 0.0000002 = watt.

**Comment by mk01** [comment]
@rolfie23 

change 
```
let f_zero = 0.0000001;
```
to
```
let f_zero = 0;
```

motivation behind was (is) that somehow I was not able to find other way than this to convert "0" to proper float output including decimals in case the value is round number. so then in domoticz the output was iterating between something like 0.3, 1, 1.6, 2 etc. 

with the firmwares prior 1, JSON.stringify is rounded to 6 decimal places, but formatting (float) stays, so that 1e-7 is then sent as 0.000000 and displayed 0.0 in domoticz (or 1.0, 2.0 etc).

the change of f_zero to 0 will solve your issue, but will just display 0 instead of 0.0.

- although while thinking a bit more now, can you perhaps try other direction, so setting
```
let f_zero = 0.00000001;
```
(or even add more leading zero(es). if you find the precision of fw 1.0, then i could use it as a permanent fix - unfortunatelly for my 4pm boxes there is not yet 1.0 available, so can't test myself)

**Comment by mk01** [comment]
@rolfie23 

the issue should have been solved in proper way.

**Comment by Mihao82** [comment]
Hi Matúš, I have a problem with my Shelly Pro 1, the script stops and ends with an error right after launching. Do you know where the problem might be, please?
<img width="1058" alt="image" src="https://github.com/mk01/shelly-2to1-mqtt/assets/142018599/9bc647b1-83e3-4ddf-a1c3-75c4061dc198">

**Comment by mk01** [comment]
@Mihao82 is the Shelly Pro 1 having energy metering ?
